export const DEFAULT_THEME: Record<string, string> = {
  primary: "#15583e",
  "primary-foreground": "#ffffff",
  secondary: "#e4ede8",
  "secondary-foreground": "#15583e",
  accent: "#22885a",
  background: "#eef0f3",
  foreground: "#0a0a0a",
  muted: "#e8eaec",
  "muted-foreground": "#6b7c6b",
  border: "#d5d8dc",
  input: "#d5d8dc",
  card: "#ffffff",
  "card-foreground": "#0a0a0a",
  "card-border": "#c9ced4",
  destructive: "#ef4444",
  success: "#16a34a",
  warning: "#f59e0b",
};
