export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  mode: "light" | "dark";
  colors: Record<string, string>;
}

export const THEME_PRESETS: ThemePreset[] = [
  // ─── LIGHT THEMES ─────────────────────────────────

  {
    id: "default-green",
    name: "OpsHub Green",
    description: "Default green theme",
    mode: "light",
    colors: {
      primary: "#15583e",
      "primary-foreground": "#ffffff",
      secondary: "#edf5f0",
      "secondary-foreground": "#15583e",
      accent: "#22885a",
      background: "#ffffff",
      foreground: "#0a0a0a",
      muted: "#f5f7f5",
      "muted-foreground": "#6b7c6b",
      border: "#d4ddd4",
      input: "#d4ddd4",
      card: "#ffffff",
      "card-foreground": "#0a0a0a",
      destructive: "#ef4444",
      success: "#16a34a",
      warning: "#f59e0b",
    },
  },
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    description: "Clean professional blue",
    mode: "light",
    colors: {
      primary: "#1e40af",
      "primary-foreground": "#ffffff",
      secondary: "#eff6ff",
      "secondary-foreground": "#1e40af",
      accent: "#3b82f6",
      background: "#ffffff",
      foreground: "#0f172a",
      muted: "#f1f5f9",
      "muted-foreground": "#64748b",
      border: "#cbd5e1",
      input: "#cbd5e1",
      card: "#ffffff",
      "card-foreground": "#0f172a",
      destructive: "#ef4444",
      success: "#22c55e",
      warning: "#f59e0b",
    },
  },
  {
    id: "royal-purple",
    name: "Royal Purple",
    description: "Elegant purple palette",
    mode: "light",
    colors: {
      primary: "#6d28d9",
      "primary-foreground": "#ffffff",
      secondary: "#f5f3ff",
      "secondary-foreground": "#6d28d9",
      accent: "#8b5cf6",
      background: "#ffffff",
      foreground: "#1e1b2e",
      muted: "#f5f3ff",
      "muted-foreground": "#7c7494",
      border: "#ddd6fe",
      input: "#ddd6fe",
      card: "#ffffff",
      "card-foreground": "#1e1b2e",
      destructive: "#ef4444",
      success: "#22c55e",
      warning: "#f59e0b",
    },
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    description: "Warm and energetic",
    mode: "light",
    colors: {
      primary: "#c2410c",
      "primary-foreground": "#ffffff",
      secondary: "#fff7ed",
      "secondary-foreground": "#c2410c",
      accent: "#ea580c",
      background: "#ffffff",
      foreground: "#1c1008",
      muted: "#fef3e2",
      "muted-foreground": "#9a7b5b",
      border: "#fed7aa",
      input: "#fed7aa",
      card: "#ffffff",
      "card-foreground": "#1c1008",
      destructive: "#dc2626",
      success: "#16a34a",
      warning: "#d97706",
    },
  },
  {
    id: "crimson-red",
    name: "Crimson",
    description: "Bold and confident",
    mode: "light",
    colors: {
      primary: "#b91c1c",
      "primary-foreground": "#ffffff",
      secondary: "#fef2f2",
      "secondary-foreground": "#b91c1c",
      accent: "#dc2626",
      background: "#ffffff",
      foreground: "#1a0a0a",
      muted: "#fef2f2",
      "muted-foreground": "#8b6b6b",
      border: "#fecaca",
      input: "#fecaca",
      card: "#ffffff",
      "card-foreground": "#1a0a0a",
      destructive: "#991b1b",
      success: "#16a34a",
      warning: "#f59e0b",
    },
  },
  {
    id: "teal-fresh",
    name: "Teal Fresh",
    description: "Modern and refreshing",
    mode: "light",
    colors: {
      primary: "#0d9488",
      "primary-foreground": "#ffffff",
      secondary: "#f0fdfa",
      "secondary-foreground": "#0d9488",
      accent: "#14b8a6",
      background: "#ffffff",
      foreground: "#0a0f0e",
      muted: "#f0fdfa",
      "muted-foreground": "#5f8a84",
      border: "#99f6e4",
      input: "#99f6e4",
      card: "#ffffff",
      "card-foreground": "#0a0f0e",
      destructive: "#ef4444",
      success: "#22c55e",
      warning: "#f59e0b",
    },
  },
  {
    id: "slate-minimal",
    name: "Slate Minimal",
    description: "Clean grayscale design",
    mode: "light",
    colors: {
      primary: "#334155",
      "primary-foreground": "#ffffff",
      secondary: "#f1f5f9",
      "secondary-foreground": "#334155",
      accent: "#475569",
      background: "#ffffff",
      foreground: "#0f172a",
      muted: "#f8fafc",
      "muted-foreground": "#94a3b8",
      border: "#e2e8f0",
      input: "#e2e8f0",
      card: "#ffffff",
      "card-foreground": "#0f172a",
      destructive: "#ef4444",
      success: "#22c55e",
      warning: "#f59e0b",
    },
  },

  // ─── DARK THEMES ──────────────────────────────────

  {
    id: "dark-default",
    name: "Dark Mode",
    description: "Default dark theme",
    mode: "dark",
    colors: {
      primary: "#22c55e",
      "primary-foreground": "#052e16",
      secondary: "#1e293b",
      "secondary-foreground": "#e2e8f0",
      accent: "#34d399",
      background: "#0f172a",
      foreground: "#f1f5f9",
      muted: "#1e293b",
      "muted-foreground": "#94a3b8",
      border: "#334155",
      input: "#334155",
      card: "#1e293b",
      "card-foreground": "#f1f5f9",
      destructive: "#f87171",
      success: "#4ade80",
      warning: "#fbbf24",
    },
  },
  {
    id: "dark-ocean",
    name: "Dark Ocean",
    description: "Deep blue dark theme",
    mode: "dark",
    colors: {
      primary: "#60a5fa",
      "primary-foreground": "#0c1929",
      secondary: "#1e3a5f",
      "secondary-foreground": "#bfdbfe",
      accent: "#3b82f6",
      background: "#0c1929",
      foreground: "#e2e8f0",
      muted: "#152238",
      "muted-foreground": "#7ba3cc",
      border: "#1e3a5f",
      input: "#1e3a5f",
      card: "#152238",
      "card-foreground": "#e2e8f0",
      destructive: "#f87171",
      success: "#4ade80",
      warning: "#fbbf24",
    },
  },
  {
    id: "dark-purple",
    name: "Dark Amethyst",
    description: "Rich purple dark theme",
    mode: "dark",
    colors: {
      primary: "#a78bfa",
      "primary-foreground": "#1a0a2e",
      secondary: "#2e1065",
      "secondary-foreground": "#e9d5ff",
      accent: "#8b5cf6",
      background: "#13091f",
      foreground: "#ede9fe",
      muted: "#1e1033",
      "muted-foreground": "#9f8cc4",
      border: "#3b1f6e",
      input: "#3b1f6e",
      card: "#1e1033",
      "card-foreground": "#ede9fe",
      destructive: "#f87171",
      success: "#4ade80",
      warning: "#fbbf24",
    },
  },
  {
    id: "dark-ember",
    name: "Dark Ember",
    description: "Warm dark with orange accents",
    mode: "dark",
    colors: {
      primary: "#fb923c",
      "primary-foreground": "#1c0f05",
      secondary: "#431407",
      "secondary-foreground": "#fed7aa",
      accent: "#f97316",
      background: "#1c1008",
      foreground: "#fef3e2",
      muted: "#2a1a0e",
      "muted-foreground": "#c49a6c",
      border: "#5c3a1e",
      input: "#5c3a1e",
      card: "#2a1a0e",
      "card-foreground": "#fef3e2",
      destructive: "#f87171",
      success: "#4ade80",
      warning: "#fbbf24",
    },
  },
  {
    id: "dark-midnight",
    name: "Midnight",
    description: "Pure dark with minimal contrast",
    mode: "dark",
    colors: {
      primary: "#e2e8f0",
      "primary-foreground": "#0f172a",
      secondary: "#1e293b",
      "secondary-foreground": "#cbd5e1",
      accent: "#94a3b8",
      background: "#020617",
      foreground: "#e2e8f0",
      muted: "#0f172a",
      "muted-foreground": "#64748b",
      border: "#1e293b",
      input: "#1e293b",
      card: "#0f172a",
      "card-foreground": "#e2e8f0",
      destructive: "#f87171",
      success: "#4ade80",
      warning: "#fbbf24",
    },
  },
  {
    id: "dark-rose",
    name: "Dark Rose",
    description: "Dark with pink/rose accents",
    mode: "dark",
    colors: {
      primary: "#fb7185",
      "primary-foreground": "#1a0810",
      secondary: "#4c0519",
      "secondary-foreground": "#fecdd3",
      accent: "#f43f5e",
      background: "#1a0810",
      foreground: "#fff1f2",
      muted: "#2a1018",
      "muted-foreground": "#c4808e",
      border: "#5c1a2a",
      input: "#5c1a2a",
      card: "#2a1018",
      "card-foreground": "#fff1f2",
      destructive: "#ef4444",
      success: "#4ade80",
      warning: "#fbbf24",
    },
  },
];

export function getPresetById(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find((p) => p.id === id);
}

export function getLightPresets(): ThemePreset[] {
  return THEME_PRESETS.filter((p) => p.mode === "light");
}

export function getDarkPresets(): ThemePreset[] {
  return THEME_PRESETS.filter((p) => p.mode === "dark");
}
