/**
 * Subject + context resolution for workflow instances.
 *
 * Templates write `{{path.to.field}}` references in subjects, emails,
 * and task titles. The engine resolves those at run time against a
 * frozen "context" object — a snapshot of the subject + manager +
 * company branding at instance-start time so that later renames never
 * retroactively change emails that have already been sent.
 *
 * The shape of the context object is the contract between this file
 * and the SUGGESTED_VARIABLES list in step-types.ts. Adding a new path
 * means adding a key here AND a row there so the editor's autocomplete
 * stays accurate.
 */

import { db } from "@/lib/db";
import { absoluteUrl } from "@/lib/url";
import type { WorkflowSubjectType } from "@prisma/client";

export interface WorkflowContext {
  subject: {
    id: string;
    firstName: string | null;
    lastName: string | null;
    fullName: string;
    email: string | null;
    jobTitle: string | null;
    department: string | null;
    startDate: Date | null;
  };
  manager: {
    id: string | null;
    firstName: string | null;
    fullName: string;
    email: string | null;
  };
  company: {
    name: string;
  };
  workflow: {
    id: string;
    name: string;
    startDate: Date;
    targetDate: Date | null;
  };
  portal: {
    url: string;
  };
}

interface BuildContextInput {
  instanceId: string;
  workflowName: string;
  startDate: Date;
  targetDate: Date | null;
  subjectType: WorkflowSubjectType;
  subjectId: string;
  /** Pre-existing portal token for this subject, if any. New tokens are
   *  generated by the portal layer in Phase 5. */
  portalToken?: string | null;
}

/**
 * Build the context blob persisted on a WorkflowInstance row at
 * instance-start time. Reads the live subject right now and freezes
 * the values into JSON.
 *
 * Phase 4 supports EMPLOYEE subjects (User rows). CANDIDATE and
 * CUSTOM subjects fall back to a minimal context derived from the
 * subjectId — Phase 5 will resolve them once the Candidate model is
 * added.
 */
export async function buildInstanceContext(
  input: BuildContextInput
): Promise<WorkflowContext> {
  const companyName =
    (await readBrandingName()) ?? "OpsHub";

  const portalUrl = input.portalToken
    ? absoluteUrl(`/portal/${input.portalToken}`)
    : absoluteUrl(`/portal/pending-${input.subjectId.slice(0, 8)}`);

  const baseWorkflow = {
    id: input.instanceId,
    name: input.workflowName,
    startDate: input.startDate,
    targetDate: input.targetDate,
  };

  if (input.subjectType === "EMPLOYEE") {
    const user = await db.user.findUnique({
      where: { id: input.subjectId },
      include: {
        manager: { select: { id: true, name: true, email: true } },
      },
    });
    if (!user) {
      // Subject vanished between trigger time and resolution. Fall back
      // to a minimal context so we don't crash the engine.
      return {
        subject: {
          id: input.subjectId,
          firstName: null,
          lastName: null,
          fullName: "(unknown employee)",
          email: null,
          jobTitle: null,
          department: null,
          startDate: null,
        },
        manager: emptyManager(),
        company: { name: companyName },
        workflow: baseWorkflow,
        portal: { url: portalUrl },
      };
    }
    const [firstName, ...rest] = (user.name ?? "").split(/\s+/);
    const lastName = rest.join(" ") || null;
    const managerFirst =
      user.manager?.name?.split(/\s+/)[0] ?? null;
    return {
      subject: {
        id: user.id,
        firstName: firstName || null,
        lastName,
        fullName: user.name || "(no name)",
        email: user.email,
        jobTitle: user.jobTitle,
        department: user.department,
        startDate: null,
      },
      manager: user.manager
        ? {
            id: user.manager.id,
            firstName: managerFirst,
            fullName: user.manager.name || "(no name)",
            email: user.manager.email,
          }
        : emptyManager(),
      company: { name: companyName },
      workflow: baseWorkflow,
      portal: { url: portalUrl },
    };
  }

  // Phase 5+ — for now CANDIDATE/CUSTOM subjects degrade gracefully.
  return {
    subject: {
      id: input.subjectId,
      firstName: null,
      lastName: null,
      fullName: `(${input.subjectType.toLowerCase()} ${input.subjectId.slice(0, 8)})`,
      email: null,
      jobTitle: null,
      department: null,
      startDate: null,
    },
    manager: emptyManager(),
    company: { name: companyName },
    workflow: baseWorkflow,
    portal: { url: portalUrl },
  };
}

function emptyManager(): WorkflowContext["manager"] {
  return {
    id: null,
    firstName: null,
    fullName: "(no manager)",
    email: null,
  };
}

async function readBrandingName(): Promise<string | null> {
  // Read directly from ThemeSetting rather than going through
  // src/lib/branding which fetches files we don't need here. The
  // engine stays lean — context build runs on every instance start.
  const row = await db.themeSetting.findUnique({
    where: { key: "branding.companyName" },
  });
  return row?.value ?? null;
}

/** Resolve a `recipient role` reference to a concrete email address by
 *  walking the context. Returns null when the role's email is missing
 *  so the caller can mark the step failed without crashing. */
export function resolveRoleEmail(
  context: WorkflowContext,
  role: "subject" | "manager" | "hr" | "it" | "owner",
  fallback?: string | null
): string | null {
  switch (role) {
    case "subject":
      return context.subject.email ?? null;
    case "manager":
      return context.manager.email ?? null;
    case "hr":
    case "it":
    case "owner":
      // Org-role mailboxes aren't first-class in Phase 4 — Phase 6 will
      // add a ThemeSetting key per role so admins can route them. For
      // now fall through to the supplied fallback (e.g. EMAIL_FROM).
      return fallback ?? null;
  }
}

/**
 * Resolve a `recipient role` reference to a User id, when one exists,
 * for actions like "assign task to manager" that need a concrete user.
 * Returns null when the role can't be resolved — the caller decides
 * whether that's a failure or a quiet skip.
 */
export function resolveRoleUserId(
  context: WorkflowContext,
  role: "specific_user" | "manager" | "hr" | "it" | "owner",
  specificUserId?: string | null
): string | null {
  switch (role) {
    case "specific_user":
      return specificUserId ?? null;
    case "manager":
      return context.manager.id;
    case "hr":
    case "it":
    case "owner":
      // Same caveat as resolveRoleEmail. Phase 6 ThemeSetting keys
      // will let admins map a User id per role.
      return null;
  }
}
